#!/usr/bin/env bash

Rscript prepare_inputs.R -i inputs -m strain_info.txt -a tp1_clusters_init.txt -b tp2_clusters_init.txt
printf "\n\n\n"

Rscript CGM/datacollection.R -a inputs/processed/tp1_clusters.txt -b inputs/processed/tp2_clusters.txt -x 0
printf "\n\n\n"

Rscript ECC/cov_epi.R -a inputs/processed/source_data.tsv -b inputs/strain_info.txt -c inputs/processed/tp1_clusters.txt -d inputs/processed/tp2_clusters.txt -x 0 -p 1 -t "010-001"
printf "\n\n\n"

Rscript merge_data.R -e results/ECCs.tsv -c results/CGM_strain_results.tsv -s inputs/strain_info.txt
printf "\n\n\n"

echo 'Finished process'
